#%%
import pandas as pd
import gams
import os
from functions import symbol_to_df, IncFile, ReadIncFilePrefix

# Path to the GAMS system directory
# gams_dir = r'C:\Users\chriko\Desktop\Balmorel_Test\Balmorel model\01 Balmorel model\base\model'
project_dir = r'C:\Users\chriko\Desktop\Balmorel_Test\Balmorel model\01 Balmorel model\base\model'
os.chdir(project_dir)

# Initialize GAMSWorkspace
ws = gams.GamsWorkspace(working_directory=project_dir)

# Define the path to your GAMS model file
model_file = 'Balmorel_ReadData'

# Load the GAMS model
model_db = ws.add_job_from_file(os.path.abspath(model_file))

# Run the GAMS file
model_db.run()
out_db = model_db.get_out_db()

#%% 1.1 Read symbol

df = symbol_to_df(out_db, 'HYDROGEN_DH2', ['Y', 'R', 'Value'])


#%% 1.2 Create IncFile

DH2 = IncFile(name='HYDROGEN_DH2_test',
              prefix="""PARAMETER HYDROGEN_DH2(YYY,CCCRRRAAA)  'Yearly demand for hydrogen at a Regional level(MWh of H2)';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
* No exogenous demand defined yet                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
*HYDROGEN_DH2(YYY,AAA)=0;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
*HYDROGEN_DH2(YYY,RRR)=0;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
TABLE HYDROGEN_DH22(CCCRRRAAA,YYY)\n""",
suffix="""\n;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
HYDROGEN_DH2(YYY,CCCRRRAAA) = HYDROGEN_DH22(CCCRRRAAA,YYY);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
HYDROGEN_DH22(CCCRRRAAA,YYY)=0;  """,
path='../data')


df_for_export = df.pivot_table(index=['R'], columns=['Y'], values=['Value']).fillna('')
df_for_export.index.name = ''
df_for_export.columns.name = ''
DH2.body = df_for_export['Value'].to_string()

DH2.save()
