[project]
authors = ["Mathias157 <mathiasros@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "spatialstudy"
platforms = ["win-64"]
version = "0.1.0"

[dependencies]
cartopy = ">=0.24.0,<0.25"
geopandas = "1.0.1.*"
matplotlib = "3.9.2.*"
ipywidgets = "8.1.3.*"
nbformat = "5.9.2.*"
numpy = "1.26.2.*"
openpyxl = "3.1.2.*"
pandas = "2.1.4.*"
plotly = "5.16.1.*"
pyarrow = "15.0.1.*"
pyproj = "3.6.1.*"
scipy = "1.11.2.*"
shapely = "2.0.2.*"
atlite = "0.2.12.*"
xarray = "2024.2.0.*"
xlrd = "2.0.1.*"
graphviz = "*"
python-graphviz = "*"
click = "*"
snakemake-minimal = "*"
pip = "*"

[pypi-dependencies]
gamsapi = { version = "==45.7.0", extras = ["transfer"] }
pybalmorel = ">=0.4.5, <0.5"

[tasks]
clustering = "cd src && snakemake -s clustering"
preprocessing = "cd src && snakemake -s preprocessing"
